var verbum = [
  "ā ab abs",
  "abeō -īre -iī -itum",
  "absum abesse āfuī",
  "ac",
  "accēdō -cēdere -cessī -cessum",
  "accidō -cidere -cidī",
  "accipiō -cipere -cēpī -ceptum",
  "ācer ācris ācre",
  "aciēs -ēī",
  "ad",
  "addō -dere -didī -ditum",
  "addūcō -ere -dūxī -ductum",
  "adeō -īre -iī -itum",
  "adeō",
  "adhibeō -hibēre -hibuī -hibitum",
  "adhūc",
  "adveniō -īre -vēnī -ventum",
  "adversus -a -um",
  "adversus (-um)",
  "advertō -vertere -vertī -versum",
  "aedēs -is",
  "aeger aegra aegrum",
  "aegrē",
  "aequē",
  "aequor aequoris",
  "aequus -a -um",
  "āēr āeris",
  "aes aeris",
  "aetās -tātis ",
  "aeternus -a -um",
  "aethēr aetheris",
  "aevum -i",
  "afferō afferre attulī allātum",
  "afficiō -ficere -fēcī -fectum",
  "ager agrī",
  "agitō -āre",
  "āgmen -minis",
  "agō agere ēgī āctum",
  "aiō",
  "albus -a -um",
  "aliēnus -a -um",
  "aliquandō",
  "aliquis -quae -quod",
  "aliter",
  "alius -a -ud",
  "alō alere aluī alitum",
  "alter altera alterum",
  "altus -a -um",
  "amīcitia -ae",
  "amīcus -a -um",
  "āmittō -mittere -mīsī -missum",
  "amnis -is",
  "amō -āre",
  "amor -ōris",
  "amplus -a -um",
  "an",
  "anima -ae",
  "animal -ālis",
  "animus -ī",
  "annus -ī",
  "ante",
  "antequam",
  "antīquus -a -um",
  "aperiō aperīre aperuī apertum",
  "appāreō -ēre -uī",
  "appellō -pellāre",
  "aptus -a -um",
  "apud",
  "aqua -ae",
  "āra -ae",
  "arbitror arbitrārī arbitrātus sum",
  "arbor arboris",
  "ārdeō ārdēre ārsī ārsum",
  "argentum -ī",
  "arma -ōrum",
  "ars artis ",
  "arvum -ī",
  "arx arcis ",
  "ascendō -ere -scendī -scēnsum",
  "aspiciō -ere -spēxī -spectum",
  "adsum adesse affuī",
  "astrum -ī",
  "at",
  "atque",
  "auctor -ōris",
  "auctōritās -ātis ",
  "audāx audācis",
  "audeō audēre ausus sum",
  "audiō -īre -īvī/-iī -ītum",
  "auferō auferre abstulī ablātum",
  "augeō augēre auxī auctum",
  "avis -is ",
  "aura -ae ",
  "aureus -a -um",
  "auris -is ",
  "aurum -ī",
  "aut",
  "autem",
  "auxilium -ī",
  "barbarus -ī",
  "beātus -a -um",
  "bellum -ī",
  "bene",
  "beneficium -ī",
  "bonus -a -um",
  "bōs bovis",
  "brevis -e",
  "breviter",
  "cadō cadere cecidī cāsum",
  "caecus -a -um",
  "caedēs -is",
  "caedō caedere cecīdī caesum",
  "caelestis -e",
  "caelum -ī",
  "campus -ī",
  "candidus -a -um",
  "canis -is",
  "canō canere cecinī cantum",
  "capiō capere cēpī captum",
  "caput capitis",
  "careō -ēre -uī",
  "carmen -inis",
  "cārus -a -um",
  "castrum -ī",
  "castus -a -um",
  "cāsus -ūs",
  "caveō cavēre cāvī cautum",
  "causa -ae",
  "cēdō cēdere cessī cessum",
  "celebrō -āre",
  "celer -is -e",
  "celeriter",
  "cēnseō cēnsēre cēnsuī cēnsum",
  "centum",
  "cernō cernere crēvī crētum",
  "certē",
  "certō -āre",
  "certus -a -um",
  "cēterum",
  "cēterus -a -um",
  "cibus -ī",
  "cingō cingere cīnxī cīnctum",
  "cinis cineris",
  "circā",
  "citus -a -um",
  "cīvis -is",
  "cīvitās -ātis ",
  "clāmor -ōris",
  "clārus -a -um",
  "classis -is",
  "claudō claudere clausī clausum",
  "coepī coepisse coeptus",
  "cōgitō -āre",
  "cōgnōscō -gnōscere -gnōvī -gnitum",
  "cōgō cōgere coēgī coāctum",
  "cohors cohortis",
  "colligō -ere -lēgī -lēctum",
  "colō colere coluī cultum",
  "color -ōris",
  "coma -ae",
  "comes comitis/",
  "committō -mittere -mīsī -missum",
  "commūnis -e",
  "comparō -āre",
  "compōnō -pōnere posuī positum",
  "concēdō -cēdere -cessī -cessum",
  "condīciō -ōnis",
  "condō -dere -didī -ditum",
  "cōnferō cōnferre contulī collātum",
  "cōnficiō -ficere -fēcī -fectum",
  "cōnfiteor cōnfitērī cōnfessus sum",
  "coniunx coniugis",
  "cōnor cōnārī cōnātus sum",
  "cōnsequor -sequī -secūtus sum",
  "cōnsilium -ī",
  "cōnsistō -sistere -stitī",
  "cōnstituō -stituere -stituī -stitūtum",
  "cōnstō -stāre -stitī",
  "cōnsuētūdo -inis",
  "cōnsul -ulis",
  "cōnsulō -sulere -suluī -sultum",
  "cōnsūmō -sūmere -sūmpsī -sūmptum",
  "contemnō -temnere -tempsī -temptum",
  "contineō -tinēre -tinuī -tentum",
  "contingō -tingere -tigī -tactum",
  "contrā",
  "conveniō -venīre -vēnī -ventum",
  "convertō -vertere -vertī -versum",
  "convīvium -iī",
  "cōpia -ae",
  "cor cordis",
  "cornu -ūs",
  "corpus corporis",
  "corrumpō -rumpere -rūpī -ruptum",
  "crēdō crēdere crēdidī crēditum",
  "creō -āre",
  "crēscō crēscere crēvī crētum",
  "crīmen -inis",
  "culpa -ae",
  "cum",
  "cūnctus -a -um",
  "cupīdō -inis",
  "cupiō -ere -īvī -ītum",
  "cūr",
  "cūra -ae",
  "cūrō -āre",
  "currō currere cucurrī cursum",
  "currus -ūs",
  "cursus -ūs",
  "custōs custōdis",
  "damnō -āre",
  "damnum -ī",
  "dē",
  "dēbeō dēbēre dēbuī dēbitum",
  "decem",
  "dēcernō -cernere -crēvī -crētum",
  "decet decēre decuīt",
  "decus decoris",
  "dēdūcō -dūcere -dūxī -ductum",
  "dēfendō -fendere -fendī -fēnsum",
  "dēferō -ferre -tulī -lātum",
  "deficiō -ficere -fēcī -fectum",
  "deinde/dein",
  "dēnique",
  "dēscendō -scendere -scendī -scēnsum",
  "dēserō -ere dēseruī dēsertum",
  "dēsīderō -āre",
  "dēsinō -sinere -siī -situm",
  "dēsum -esse -fuī",
  "deus -ī; dea -ae ",
  "dexter -tra -trum",
  "dīcō dīcere dīxī dictum",
  "diēs diēī",
  "differō differre distulī dīlātum",
  "difficilis -e",
  "dīgnitās -ātis",
  "dīgnus -a -um",
  "dīligō -ligere -lēxī -lēctum",
  "dīmittō -mittere -mīsī -missum",
  "discēdō -ere -cessī -cessum",
  "disciplīna -ae ",
  "discō -ere didicī",
  "diū",
  "dīversus -a -um",
  "dīves dīvitis",
  "dīvidō -ere dīvīsī dīvīsum",
  "dīvitiae -ārum",
  "dīvus -a -um",
  "dō dare dedī datum",
  "doceō -ēre -uī doctum",
  "doleō -ēre doluī",
  "dolor -ōris",
  "dolus -ī",
  "dominus -ī; domina -ae",
  "domus -ūs",
  "dōnec",
  "dōnō -āre",
  "dōnum -ī",
  "dormiō -īre",
  "dubitō -āre",
  "dubius -a -um",
  "dūcō dūcere dūxī ductum",
  "dulcis -e",
  "dum",
  "duo duae duo",
  "dūrus -a -um",
  "dux ducis",
  "ecce",
  "ēdīcō -dīcere -dīxī -dictum",
  "ēdō ēdere ēdidī ēditum",
  "ēdūcō -dūcere -dūxī -ductum",
  "efficiō -ficere -fēcī -fectum",
  "effundō -fundere -fūdī -fūsum",
  "ego meī mihi mē",
  "ēgredior ēgredī ēgressus sum",
  "ēgregius -a -um",
  "ēligō ēligere ēlēgī ēlēctum",
  "enim",
  "eō īre iī/īvī itum",
  "eō",
  "epistula -ae",
  "eques equitis",
  "equus -ī",
  "ergō",
  "ēripiō -ripere -ripuī -reptum",
  "errō -āre",
  "error -ōris",
  "et",
  "etiam",
  "ex / ē",
  "excipiō -cipere -cēpī -ceptum",
  "exemplum -ī",
  "exeō -īre -iī -itum",
  "exerceō -ercēre -ercuī -ercitum",
  "exercitus -ūs",
  "exigō -igere -ēgī -āctum",
  "exīstimō -āre",
  "experior -perīrī -pertus sum",
  "exsilium -ī",
  "exspectō -āre",
  "extrēmus -a -um",
  "fābula -ae",
  "faciēs -ēī",
  "facilis -e",
  "facinus facinoris",
  "faciō facere fēcī factum",
  "factum -ī",
  "fallō fallere fefellī falsum",
  "falsus -a -um",
  "fāma -ae",
  "famēs -is",
  "familia -ae",
  "fateor fatērī fassus sum",
  "fātum -ī",
  "fax facis",
  "fēlīciter",
  "fēlīx -īcis",
  "fēmina -ae",
  "ferē",
  "ferō ferre tulī lātum",
  "ferrum -ī",
  "ferus -a -um",
  "fessus -a -um",
  "fidēlis -e",
  "fidēs -eī",
  "fīlia -ae ; fīlius -ī",
  "fingō fingere fīnxī fīctum",
  "fīnis -is",
  "fīō fierī factus sum",
  "flamma -ae",
  "fleō flēre flēvī flētum",
  "flōs flōris",
  "fluctus -ūs",
  "flūmen -inis",
  "fluō fluere fluxī fluxum",
  "foedus -a -um",
  "fōns fontis",
  "for fārī fātus sum",
  "fōrma -ae",
  "fors fortis ",
  "forsitan",
  "fortasse",
  "forte",
  "fortis -e",
  "fortūna -ae ",
  "forum -ī",
  "frangō frangere frēgī frāctum",
  "frāter frātris",
  "frequēns -ntis",
  "frōns frontis ",
  "frūctus -ūs",
  "frūmentum -ī",
  "fruor fruī frūctus sum",
  "frūstrā",
  "fuga -ae",
  "fugiō fugere fūgī fugitum",
  "fugō -āre",
  "fundō fundere fūdī fūsum",
  "fūnus fūneris",
  "furor -ōris",
  "fore",
  "gaudeō gaudēre gāvīsus sum",
  "gaudium -ī",
  "gēns gentis",
  "genus generis",
  "gerō gerere gessī gestum",
  "gīgnō gīgnere genuī genitum",
  "gladius -ī",
  "glōria -ae",
  "gradus -ūs",
  "grātia -ae",
  "grātus -a -um",
  "gravis -e",
  "habeō habēre habuī habitum",
  "haud",
  "hic haec hoc",
  "hīc",
  "hiems hiemis",
  "hodiē",
  "homō hominis",
  "honestus -a -um",
  "honor -ōris",
  "hōra -ae",
  "hortor hortārī hortātus sum",
  "hospes hospitis",
  "hostis -is",
  "hūc",
  "hūmānus -a -um",
  "humus -ī",
  "iaceō iacēre iacuī",
  "iaciō iacere iēcī iactum",
  "iam",
  "ibi",
  "īctus -ūs",
  "īdem eadem idem",
  "ideō",
  "igitur",
  "ignis -is",
  "ille illa illud",
  "illīc",
  "illūc",
  "imāgō -inis",
  "imperātor -ōris",
  "imperium -ī",
  "imperō -āre",
  "impetus -ūs",
  "impleō -ēre -plēvī -plētum",
  "impōnō -ere -posuī -positum",
  "in",
  "incidō incidere incidī",
  "incipiō -cipere -cēpī -ceptum",
  "inde",
  "indicō -āre",
  "īnferō īnferre intulī illātum",
  "īnferus -a -um",
  "ingenium -ī",
  "ingēns ingentis",
  "ingrātus -a -um",
  "ingredior -gredī -gressus sum",
  "inimīcus -a -um",
  "initium -ī",
  "iniūria -ae",
  "inquam",
  "īnstituō -stituere -stituī -stitūtum",
  "īnsula -ae",
  "integer -gra -grum",
  "intellegō -legere -lēxī -lēctum",
  "intendō -tendere -tendī -tentum",
  "inter",
  "interficiō -ficere -fēcī -fectum",
  "interim",
  "interrogō -āre",
  "intersum -esse -fuī",
  "intrā",
  "intrō -āre",
  "inveniō -venīre -vēnī -ventum",
  "invidia -ae",
  "ipse ipsa ipsum",
  "īra irae",
  "īrāscor īrāscī īrātus sum",
  "is ea id",
  "iste ista istud",
  "ita",
  "itaque",
  "item",
  "iter itineris",
  "iterum",
  "iubeō iubēre iussī iussum",
  "iūdex iūdicis",
  "iūdicium -ī",
  "iūdicō -āre",
  "iugum -ī",
  "iungō iungere iūnxī iūnctum",
  "iūrō -āre",
  "iūs iūris",
  "iūstus -a -um",
  "iuvenis -is",
  "iuvō iuvāre iūvī iūtum",
  "labor -ōris",
  "labōrō -āre",
  "lacrima -ae",
  "laedō laedere laesī laesum",
  "laetus -a -um",
  "lapis lapidis",
  "lateō latēre latuī",
  "latus -eris",
  "lātus -a -um",
  "laudō -āre",
  "laus laudis ",
  "lēgātus -ī",
  "legiō -ōnis ",
  "legō legere lēgī lēctum",
  "levis -e",
  "lēx lēgis",
  "liber librī",
  "līber lībera līberum",
  "lībertās -ātis",
  "libet libēre libuit or libitum est",
  "libīdō -inis",
  "licet licēre licuit licitum est",
  "licet",
  "līmen līminis",
  "lingua -ae",
  "littera -ae",
  "lītus -oris",
  "locus -ī",
  "longē",
  "longus -a -um",
  "loquor loquī locūtus sum",
  "lūmen luminis",
  "lūna -ae",
  "lūx lūcis",
  "maestus -a -um",
  "magis",
  "magister magistrī",
  "māgnitūdō -inis",
  "māgnus -a -um",
  "māiōrēs māiōrum",
  "male",
  "mālō mālle māluī",
  "malus -a -um",
  "maneō manēre mānsī mānsum",
  "manus -ūs ",
  "mare -is",
  "marītus -ī",
  "māter mātris",
  "māteria -ae",
  "medius -a -um",
  "membrum -ī",
  "meminī meminisse",
  "memoria -ae",
  "mēns mentis",
  "mēnsa -ae",
  "mereō merēre meruī meritum",
  "metuō metuere metuī",
  "metus -ūs",
  "meus -a -um",
  "mīles -itis",
  "mīlle (pl.) mīlia",
  "mīror mīrārī mīrātus sum",
  "misceō miscēre miscuī mixtum",
  "miser misera miserum",
  "mittō mittere mīsī missum",
  "modo",
  "modus -ī",
  "moenia -ium pl.",
  "mollis -e",
  "moneō monēre monuī monitum",
  "mōns montis",
  "mora -ae",
  "morbus -ī",
  "morior morī mortuus sum",
  "moror morārī morātus sum",
  "mors mortis",
  "mortālis -e",
  "mōs mōris",
  "moveō -ēre mōvī mōtum",
  "mox",
  "mulier -eris ",
  "multitūdō -inis ",
  "multus -a -um",
  "mundus -ī",
  "mundus -a -um",
  "mūnus mūneris",
  "mūrus -ī",
  "mūtō -āre",
  "nam or namque",
  "narrō -āre",
  "nāscor nāscī nātus sum",
  "nātūra -ae ",
  "nātus -ī",
  "nāvis -is ",
  "ne",
  "nē",
  "nec",
  "necesse",
  "necessitās -tātis ",
  "nefās indecl.",
  "negō -āre",
  "negōtium -ī",
  "nēmō",
  "nemus nemoris",
  "neque",
  "nesciō -scīre",
  "nisi",
  "nī",
  "niger nigra nigrum",
  "nihil",
  "nīl",
  "nimis or nimium",
  "nimius -a -um",
  "nōbilis -e",
  "noceō nocēre nocuī",
  "nōlō nōlle nōluī",
  "nōmen -inis",
  "nōn",
  "nōndum",
  "nōs nostrum/nostrī nōbīs nōs",
  "nōscō nōscere nōvī nōtum",
  "noster nostra nostrum",
  "nōtus -a -um",
  "novus -a -um",
  "nox noctis",
  "nūdus -a -um",
  "nūllus -a -um",
  "num",
  "nūmen -inis",
  "numerus -ī",
  "numquam",
  "nunc",
  "nūntius -ī",
  "ob",
  "occīdō -cīdere -cīdī -cīsum",
  "occupō -āre",
  "occurrō -currere -cucurrī -cursum",
  "oculus -ī",
  "ōdī ōdisse",
  "odium -ī",
  "offerō offerre obtulī oblātum",
  "officium -ī",
  "ōlim",
  "omnis -e",
  "onus oneris",
  "opera -ae",
  "oportet -ēre -uit",
  "oppidum -ī",
  "ops opis",
  "optō -āre",
  "opus operis",
  "ōrātiō -ōnis",
  "orbis -is",
  "ōrdō -īnis",
  "orior orīrī ortus sum",
  "ōrō -āre",
  "ōs ōris",
  "os ossis",
  "ostendō ostendere ostendī ostentum",
  "ōtium -ī",
  "paene",
  "pār paris",
  "parcō parcere pepercī parsum",
  "parēns -ntis",
  "pāreō pārēre pāruī",
  "pariō parere peperī partum",
  "parō -āre",
  "pars partis ",
  "parum",
  "parvus -a -um",
  "pateō patēre patuī",
  "pater patris",
  "patior patī passus sum",
  "patria -ae ",
  "paucī -ae -a",
  "paulō",
  "paulum",
  "pauper -eris",
  "pāx pācis ",
  "peccō -āre",
  "pectus -oris",
  "pecūnia -ae ",
  "pecus -oris",
  "pellō pellere pepulī pulsum",
  "pendō pendere pependī pēnsum",
  "per",
  "perdō -dere -didī -ditum",
  "pereō -īre -iī -itum",
  "pergō pergere perrēxī perrēctum",
  "perīculum -ī",
  "permittō -mittere -mīsī -missum",
  "perpetuus -a -um",
  "pertineō -tinēre -tinuī",
  "perveniō -venīre -vēnī -ventum",
  "pēs pedis",
  "petō petere petīvī petītum",
  "pietās -tātis ",
  "pius -a -um",
  "placeō placēre placuī placitum",
  "plēbs plēbis ",
  "plēnus -a -um",
  "plērumque",
  "plērus- plēra- plērumque",
  "poena -ae ",
  "poēta -ae",
  "pondus ponderis",
  "pōnō pōnere posuī positum",
  "pontus -ī",
  "populus -ī",
  "porta -ae ",
  "portō -āre",
  "pōscō pōscere popōscī",
  "possum posse potuī",
  "post",
  "posteā",
  "posterus -a -um",
  "postquam",
  "potēns potentis",
  "potestās -ātis ",
  "potis -e",
  "praebeō -ēre -uī -itum",
  "praeceptum -ī",
  "praecipiō -cipere -cēpī -ceptum",
  "praeda -ae ",
  "praemium -ī",
  "praesēns -ntis",
  "praesidium -ī",
  "praestō -stāre -stitī -stitum",
  "praeter",
  "praetereā",
  "praetor -ōris",
  "precor -ārī",
  "premō premere pressī pressum",
  "pretium -ī",
  "prex precis ",
  "prīmum",
  "prīmus -a -um",
  "prīnceps -cipis",
  "prīncipium -ī",
  "prior prius",
  "prīvātus -a -um",
  "prius or priusquam",
  "prō",
  "probō -āre",
  "prōcēdō -cēdere -cessī -cessum",
  "procul",
  "prōdō prōdere prōdidī prōditum",
  "proelium -ī",
  "proficīscor -ficīscī -fectus sum",
  "prohibeō -ēre -uī -itum",
  "prōmittō -mittere -mīsī -missum",
  "prope",
  "properō -āre",
  "prōpōnō -pōnere -posuī -positum",
  "proprius -a -um",
  "propter",
  "prōsum prodesse profuī",
  "prōtinus",
  "prōvincia -ae",
  "pūblicus -a -um",
  "pudor pudōris",
  "puella -ae",
  "puer puerī",
  "pūgna -ae",
  "pugnō -āre",
  "pulcher -chra -chrum",
  "putō -āre",
  "quā",
  "quaerō -rere -sīvī -sītum",
  "quālis -e",
  "quam",
  "quamquam",
  "quamvīs",
  "quandō",
  "quantum",
  "quantus -a -um",
  "quārē",
  "quasi",
  "quattuor",
  "que",
  "quemadmodum",
  "queror querī questus sum",
  "quī quae quod",
  "quia",
  "quīcumque quaecumque quodcumque",
  "quīdam quaedam quoddam",
  "quidem",
  "quiēscō quiēscere quiēvī quiētum",
  "quīn",
  "quīppe",
  "quis quid",
  "quisquam quicquam/quidquam",
  "quisque quaeque quidque",
  "quisquis quidquid",
  "quō",
  "quōmodo",
  "quondam",
  "quoniam",
  "quoque",
  "quotiēns",
  "rapiō rapere rapuī raptum",
  "rārus -a -um",
  "ratiō -ōnis",
  "recēdō -cēdere -cessī -cessum",
  "recēns -ntis",
  "recipiō -cipere -cēpī -ceptum",
  "rēctus -a -um",
  "reddō -dere -didī -ditum",
  "redeō -īre -iī -itum",
  "referō referre rettulī relātum",
  "regiō -ōnis ",
  "rēgius -a -um",
  "rēgnum -ī",
  "regō regere rēxī rēctum",
  "relinquō -linquere -līquī -lictum",
  "reliquus -a -um",
  "reor rērī rātus sum",
  "reperiō -perīre -pperī -pertum",
  "repetō -petere -petīvī -petītum",
  "rēs reī",
  "respicio -ere -spēxī -spectum",
  "respondeō -spondēre -spondī -spōnsum",
  "retineō -tinēre -tinuī -tentum",
  "revertō -vertere -vertī",
  "revocō -āre",
  "reus -ī",
  "rēx rēgis",
  "rīdeō -ēre rīsī rīsum",
  "rīpa -ae ",
  "rogō -āre",
  "rumpō rumpere rūpī ruptum",
  "rūrsus",
  "rūs rūris",
  "sacer sacra sacrum",
  "sacerdōs -dōtis",
  "saeculum -ī",
  "saepe",
  "saevus -a -um",
  "salūs -ūtis",
  "sānctus -a -um",
  "sanguis -inis",
  "sānus -a -um",
  "sapiēns -ntis",
  "sapientia -ae",
  "satis",
  "sat",
  "saxum -ī",
  "scelus -eris",
  "scientia -ae ",
  "scīlicet",
  "sciō -īre -īvī/-iī -ītum",
  "scrībō scrībere scrīpsī scrīptum",
  "secundus -a -um",
  "sēcūrus -a -um",
  "sed",
  "sedeō sedēre sēdī sessum",
  "sēdēs -is",
  "semel",
  "semper",
  "senātus -ūs",
  "senex -is",
  "sēnsus -ūs",
  "sententia -ae ",
  "sentiō sentīre sēnsī sēnsum",
  "sepulcrum -ī",
  "sequor sequī secūtus sum",
  "sermō -ōnis",
  "serviō -īre",
  "servō -āre",
  "servus -ī",
  "seu",
  "sī",
  "sīc",
  "sīcut",
  "sīdus -eris",
  "sīgnum -ī",
  "silva -ae ",
  "similis -e",
  "simul",
  "sine",
  "singulī -ae -a",
  "sinō sinere sīvī situm",
  "sinus -ūs",
  "sīve",
  "socius -a -um",
  "sōl sōlis",
  "soleō -ēre -uī -itum",
  "sōlum",
  "solvō solvere solvī solūtum",
  "sōlus -a -um",
  "somnus -ī",
  "sonō sonāre sonuī sonitum",
  "soror -ōris",
  "sors sortis",
  "spargō spargere sparsī sparsum",
  "spatium -ī",
  "speciēs -ēī ",
  "spectō -āre",
  "spērō -āre",
  "spēs speī ",
  "spīritus -ūs",
  "statim",
  "statuō -ere -uī -ūtum",
  "stella -ae",
  "stō stāre stetī statum",
  "studeō -ēre -uī",
  "studium -ī",
  "sub",
  "subeō -īre -iī -itum",
  "subitō",
  "sui sibi sē/sēsē",
  "sum esse fuī futūrum",
  "sūmō sūmere sūmpsī sūmptum",
  "super",
  "superbus -a -um",
  "superī -ōrum",
  "superō -āre",
  "supersum -esse -fuī",
  "superus -a -um",
  "supplicium -ī",
  "suprā",
  "surgō surgere surrēxī surrēctum",
  "suscipiō -cipere -cēpī ceptum",
  "sustineō sustinēre sustinuī sustentum",
  "suus -a -um",
  "taceō -ēre -uī -itum",
  "tālis tāle",
  "tam",
  "tamen",
  "tamquam",
  "tandem",
  "tangō tangere tetigī tāctum",
  "tantum",
  "tantummodo",
  "tantus -a -um",
  "tardus -a -um",
  "tēctum -ī",
  "tegō tegere tēxī tēctum",
  "tellus tellūris",
  "tēlum -ī",
  "tempestas -tātis",
  "templum -ī",
  "tempus -oris",
  "tendō tendere tetendī tentum",
  "tenebrae -brārum",
  "teneō -ēre -uī tentum",
  "tener -era -erum",
  "temptō -āre",
  "tergum -ī",
  "terra -ae",
  "terreō terrēre terruī territum",
  "tertius -a -um",
  "testis -is",
  "timeō -ēre -uī",
  "timor -ōris",
  "tollō tollere sustulī sublātum",
  "tot",
  "tōtus -a -um",
  "trādō -dere -didī -ditum",
  "trahō trahere trāxī trāctum",
  "trānseō -īre -iī -itum",
  "trēs tria",
  "tribūnus -ī",
  "trīstis -e",
  "tū tuī tibi tē",
  "tum or tunc",
  "turba -ae ",
  "turbō -āre",
  "turpis -e",
  "tūtus -a -um",
  "tuus -a -um",
  "vacō vacāre",
  "vacuus -a -um",
  "vagus -a -um",
  "valeō valēre valuī",
  "validus -a -um",
  "vanus -a -um",
  "varius -a -um",
  "vātēs -is",
  "ubi",
  "ve",
  "vehō vehere vēxī vectum",
  "vel",
  "velut",
  "veniō venīre vēnī ventum",
  "ventus -ī",
  "verbum -ī",
  "vērē",
  "vereor verērī veritus sum",
  "vērō",
  "vertō vertere vertī versum",
  "vērus -a -um",
  "vester vestra vestrum",
  "vestīgium -ī",
  "vestis -is ",
  "vetō -āre vetuī vetītum",
  "vetus veteris",
  "via -ae",
  "vīcīnus -a -um",
  "victor -ōris",
  "victōria -ae",
  "videō vidēre vīdī vīsum",
  "vincō vincere vīcī victum",
  "vinculum -ī",
  "vīnum -ī",
  "vir virī",
  "virgō -inis",
  "virtūs -ūtis",
  "vīs",
  "vīta -ae ",
  "vitium -ī",
  "vītō -āre",
  "vīvō vīvere vīxī vīctum",
  "vix",
  "ūllus -a -um",
  "ultimus -a -um",
  "ultrā",
  "umbra -ae ",
  "umquam",
  "unda -ae",
  "unde",
  "undique",
  "ūnus -a -um",
  "vocō -āre",
  "volō velle voluī",
  "volucer -cris -cre",
  "volucris -is",
  "voluntās -ātis",
  "voluptās -ātis",
  "vōs",
  "vōtum -ī",
  "vōx vōcis",
  "urbs urbis",
  "ūsque",
  "ūsus -ūs",
  "ut, utī",
  "uterque utraque utrumque",
  "ūtilis -e",
  "ūtor ūtī ūsus sum",
  "utrum",
  "vulgō",
  "vulgus -ī",
  "vulnus -eris",
  "vultus -ūs",
  "uxor uxōris"
]


function novumVerbum() {
  var randomNumber = Math.floor(Math.random() * (verbum.length));
    document.getElementById('verbumDisplay').innerHTML = verbum[randomNumber];
}
